SELECT * INTO WORLDCUP FROM CRICKET

SELECT * FROM IPL

SELECT * INTO T20 FROM CRICKET WHERE 1>2

SELECT * INTO IPL FROM CRICKET WHERE 1>2

INSERT INTO IPL 
SELECT * FROM CRICKET WHERE NAMEE LIKE '_A_____'

INSERT INTO IPL SELECT * FROM Cricket WHERE NAMEE LIKE '_A_____%'TRUNCATE TABLE IPLSELECT * FROM IPL