DROP TABLE L3

CREATE TABLE L3
(
	ENROLLMENT_NO		VARCHAR(20),
	NAMEE				VARCHAR(25),
	CPI					DECIMAL(5,2),
	BIRTHDATE			DATETIME
)

ALTER TABLE L3
ADD CITY VARCHAR(50) NULL, BACKLOG INT NOT NULL

ALTER TABLE L3
ALTER COLUMN NAMEE VARCHAR(35)

ALTER TABLE L3
ALTER COLUMN CPI INT 

SP_RENAME 'L3.ENROLLMENT_NO','ENO','COLUMN'

ALTER TABLE L3
DROP COLUMN CITY 

SP_RENAME 'L3','LAB3'

ALTER TABLE LAB3
DROP COLUMN BACKLOG

ALTER TABLE LAB3
ALTER COLUMN NAMEE VARCHAR(35) NOT NULL

SP_RENAME 'LAB3.BIRTHDATE','BDATE','COLUMN'

ALTER TABLE LAB3
ALTER COLUMN ENO VARCHAR(12)