CREATE TABLE STUDENT
(	
	RNO   INT,
	NAMEE VARCHAR(50),
	BRANCH VARCHAR(50),
	SPI    DECIMAL(8,2),
	BKLOG  INT,
)

CREATE VIEW PERSONAL
AS
SELECT * FROM BACKLOG  
 
CREATE VIEW STUDENT_DETAILS
AS
SELECT NAMEE,BRANCH,SPI  FROM STUDENT

CREATE VIEW ACADEMIC 
AS
SELECT RNO,NAMEE,BRANCH FROM STUDENT

CREATE VIEW STUDENT_DATA 
AS
SELECT * FROM STUDENT WHERE BKLOG>2

CREATE VIEW STUDENT_PATTERN 
AS
SELECT RNO,NAMEE,BRANCH FROM STUDENT WHERE NAMEE LIKE '___'

INSERT INTO ACADEMIC VALUES  (107,'MEET','ME')

UPDATE STUDENT_DETAILS SET BRANCH='ME' WHERE NAMEE='AMIT'

DELETE FROM ACADEMIC WHERE RNO=104

CREATE VIEW DISPLAY
AS
SELECT * FROM STUDENT WHERE SPI>8.5

CREATE VIEW BACKLOG
AS
SELECT * FROM STUDENT WHERE BKLOG=0