CREATE TABLE WEBSITE
(
	STUD			INT,
	FIRTSNAME		VARCHAR(50),
	LASTNAME		VARCHAR(25),
	WEBSITE			VARCHAR(50),
	CITY			VARCHAR(25),
	DIVISION		VARCHAR(20)
)

SELECT FIRTSNAME FROM WEBSITE WHERE FIRTSNAME LIKE 'K%'

SELECT FIRTSNAME FROM WEBSITE WHERE FIRTSNAME LIKE '_____'

SELECT * FROM WEBSITE WHERE FIRTSNAME LIKE '[A-H]%' 