CREATE TABLE STUDENT12
(	
	RNO				INT,
	NAMEE			VARCHAR(50),
	CITY			VARCHAR(50),
	DID				INT
)

CREATE TABLE ACADEMIC1
(
	RNO			INT,
	SPI			DECIMAL(8,2),
	BACKLOG		INT
)

CREATE TABLE DEPARTMENT
(
	DID		INT,
	DNAME	VARCHAR(50)
)

SELECT * FROM STUDENT12 WHERE DID = (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER')

SELECT * FROM STUDENT12 WHERE RNO IN(SELECT RNO FROM ACADEMIC1 WHERE SPI>8)

SELECT * FROM STUDENT12 WHERE DID = (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER') AND CITY='RAJKOT'

SELECT COUNT(RNO) AS TOTAL FROM STUDENT12 WHERE DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL') 

SELECT NAMEE 
FROM STUDENT12 
WHERE RNO IN(SELECT RNO FROM ACADEMIC1 WHERE RNO IN(SELECT MAX(SPI) FROM ACADEMIC1))

SELECT * FROM STUDENT12 WHERE RNO IN(SELECT RNO FROM ACADEMIC1 WHERE BACKLOG>1)

SELECT NAMEE
FROM STUDENT12
WHERE RNO =
(SELECT RNO FROM ACADEMIC1 WHERE SPI =
(SELECT MAX(SPI) FROM ACADEMIC1 WHERE SPI
<(SELECT MAX(SPI) FROM ACADEMIC1)))

SELECT NAMEE FROM STUDENT12 
WHERE DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME IN('COMPUTER','ELECTRICAL'))

SELECT NAMEE FROM STUDENT12 WHERE DID =(SELECT DID FROM STUDENT12 WHERE RNO=102) 

SELECT NAMEE FROM STUDENT12 WHERE RNO IN(SELECT RNO FROM ACADEMIC1 WHERE SPI>9) AND DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL')

